#!/bin/sh
# Xcode Cloud runs this immediately after cloning, before it looks for the
# project. It has to, because two things this build needs are deliberately not
# in the repository:
#
#   app/Earned.xcodeproj    generated by XcodeGen from app/project.yml. Checking
#                           in a generated project means the checked-in copy and
#                           the spec drift, and the drift is invisible until a
#                           target silently loses a setting — which has already
#                           happened once here, with the monitor's entitlements.
#   app/Earned/Backend.plist  carries the Supabase URL and publishable key. The
#                           key is public by design, but the project it points
#                           at is not the repository's business.
#
# Without this script the build fails with "Project Earned.xcodeproj does not
# exist at app/Earned.xcodeproj", which is accurate and unhelpful.
#
# Set SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY as environment variables on the
# Xcode Cloud workflow. Both are safe to put there: the publishable key is the
# one meant to ship inside the app. The secret key must never appear here.
set -e

echo "--- Installing XcodeGen"
brew install xcodegen

echo "--- Generating the project from app/project.yml"
cd "$CI_PRIMARY_REPOSITORY_PATH"
xcodegen generate --spec app/project.yml --project app

# The generated project must match the checked-in entitlements exactly. This is
# the same guard CI runs on every push, repeated here because Xcode Cloud is
# the one place that *signs* — and an entitlement silently regenerated as an
# empty dict produces an app that installs, runs, and cannot shield anything.
echo "--- Checking the entitlements survived generation"
git diff --exit-code -- 'app/**/*.entitlements'

echo "--- Checking the release configuration"
python3 tools/validate-release-config.py

echo "--- Writing Backend.plist"
if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_PUBLISHABLE_KEY" ]; then
  # Failing here rather than building without it. Earned works with no backend
  # (S8), so the build would succeed and the testers would get an app with no
  # accounts, no partners and no social layer — a broken beta that looks like a
  # product decision.
  echo "SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY must be set on the workflow." >&2
  echo "Without them this build ships with no backend at all." >&2
  exit 1
fi

cat > app/Earned/Backend.plist <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>SupabaseURL</key>
	<string>${SUPABASE_URL}</string>
	<key>SupabasePublishableKey</key>
	<string>${SUPABASE_PUBLISHABLE_KEY}</string>
</dict>
</plist>
PLIST

plutil -lint app/Earned/Backend.plist
echo "--- Ready"
