// Generated by backend/tools/grant_vectors.sh — real keys, real signatures.
//
// DO NOT REGENERATE TO FIX A FAILING TEST. These bytes were produced by
// Postgres composing a document, OpenSSL signing it, and the schema serving it
// back, which is exactly the path production takes. A test that stops passing
// against them is reporting that Swift and the server have come to disagree
// about the wire format — the most silent failure this system has, and the
// only place all three implementations are checked against one another.
//
// The private keys were generated in a temporary directory and thrown away;
// only the public halves are here, and public keys are public.

import Foundation

enum GrantVectors {
    /// The offline root key's public half. Signs key sets, never grants.
    static let rootPublicKey = Data(base64Encoded: "MQ5D9ZK+FNQZyRdUSl3uenwiwgsiYhMAkW8XVQk0TrM=")!

    /// Version 1: g1 introduced, not yet promoted. A key set can never show a
    /// brand-new key as anything but `next` — publication is what earns
    /// promotion — so this is what "told about, not yet trusted to sign"
    /// looks like on the wire.
    static let keySetV1 = #"""
{"keys": [{"alg": "ed25519", "kid": "g1", "state": "next", "public": "ud1OMGyGAiBU5P4Zz87jdZDTSroNLFndDYYqfJDdlbg=", "not_after": null, "not_before": "2026-08-31T11:39:01.104048+00:00"}], "revoked": [], "version": 1, "issued_at": "2026-08-31T11:39:01.148407+00:00"}
"""#
    static let keySetV1Signature = Data(base64Encoded: "0KcGmlsgVpIimYd4X52xaoJN5dqnSie9Lhip2CbrDfwcgphguwhQdPSiKzBDKL4Ud6BYukbHh18hoJ7t20Y3Cg==")!

    /// Version 2: g1 promoted and republished. This is the set in force when
    /// the grant below was signed, and the one the happy path uses.
    static let keySetV2 = #"""
{"keys": [{"alg": "ed25519", "kid": "g1", "state": "current", "public": "ud1OMGyGAiBU5P4Zz87jdZDTSroNLFndDYYqfJDdlbg=", "not_after": null, "not_before": "2026-08-31T11:39:01.104048+00:00"}], "revoked": [], "version": 2, "issued_at": "2026-08-31T11:39:01.295982+00:00"}
"""#
    static let keySetV2Signature = Data(base64Encoded: "S7Gs+W/QEnRAEGZT6VfVf32GBlvpV1a+tzLJq3hDucERw2fDTDjA+SNAxxmfVTkrVfmLdAS0MsKGRKwBcwV8Bg==")!

    /// Version 3: g2 introduced alongside g1. Rotation begins.
    static let keySetV3 = #"""
{"keys": [{"alg": "ed25519", "kid": "g1", "state": "current", "public": "ud1OMGyGAiBU5P4Zz87jdZDTSroNLFndDYYqfJDdlbg=", "not_after": null, "not_before": "2026-08-31T11:39:01.104048+00:00"}, {"alg": "ed25519", "kid": "g2", "state": "next", "public": "lr4lnGsVDYce7pWUYYRwXcCOwYNlF7AwjBhoWyYgiGA=", "not_after": null, "not_before": "2026-08-31T11:39:02.04729+00:00"}], "revoked": [], "version": 3, "issued_at": "2026-08-31T11:39:02.09038+00:00"}
"""#
    static let keySetV3Signature = Data(base64Encoded: "s6rT1ZZPs6J4e9K1Ck/e8o3h7Q5v+jCBd5p1MlV9G3XzNScCA/RRwS7GW54FjGUxsWXFawqSDUWqZ/QMJSu+AA==")!

    /// Version 4: g2 promoted, g1 retired. A retired key must still verify
    /// what it signed while it was current — that is the whole difference
    /// between retiring a key and revoking one.
    static let keySetV4 = #"""
{"keys": [{"alg": "ed25519", "kid": "g2", "state": "current", "public": "lr4lnGsVDYce7pWUYYRwXcCOwYNlF7AwjBhoWyYgiGA=", "not_after": null, "not_before": "2026-08-31T11:39:02.04729+00:00"}, {"alg": "ed25519", "kid": "g1", "state": "retired", "public": "ud1OMGyGAiBU5P4Zz87jdZDTSroNLFndDYYqfJDdlbg=", "not_after": "2026-09-30T11:39:02.191614+00:00", "not_before": "2026-08-31T11:39:01.104048+00:00"}], "revoked": [], "version": 4, "issued_at": "2026-08-31T11:39:02.237206+00:00"}
"""#
    static let keySetV4Signature = Data(base64Encoded: "BRbz/KKLpP/FBaSfIg7EZtMx5MA9SRBSgmDtW8JVtGBN2N6xuQBuAbW0nSx67hUTALBP6HEFTbr7oC2T8N8nDw==")!

    /// Version 5: g1 revoked. The kill list, and it reaches backwards.
    static let keySetV5 = #"""
{"keys": [{"alg": "ed25519", "kid": "g2", "state": "current", "public": "lr4lnGsVDYce7pWUYYRwXcCOwYNlF7AwjBhoWyYgiGA=", "not_after": null, "not_before": "2026-08-31T11:39:02.04729+00:00"}], "revoked": [{"kid": "g1", "revoked_at": "2026-08-31T11:39:02.341306+00:00"}], "version": 5, "issued_at": "2026-08-31T11:39:02.385234+00:00"}
"""#
    static let keySetV5Signature = Data(base64Encoded: "8KI7fFjpISEJBZp8IKSZFmPUjcDexsNoU1d8jqPYu5Sou3th3/+Z4XuVyN8hboIA8McJw02jNu9ohaGxlFVGAQ==")!

    /// A grant for a real 2-of-2 request, signed by g1.
    static let grant = #"""
{"kid": "g1", "roster": [{"at": "2026-08-31T11:39:01.715934+00:00", "vote": "approve", "partner_display_name": "Mom"}, {"at": "2026-08-31T11:39:01.805544+00:00", "vote": "approve", "partner_display_name": "Dave"}], "decision": "granted", "decided_at": "2026-08-31T11:39:01.805544+00:00", "policy_digest": "sha256:60d5ec96060ffd4cf70ce897ddc21e27ce9b96a9245a84a096bac921f0aa3541", "server_grant_id": "e947e217-fef8-494e-95fa-0ac1a30df4c9", "client_request_id": "85a94f3b-6bb9-48a0-be15-689d5a38b4fa"}
"""#
    static let grantSignature = Data(base64Encoded: "8TdN7gyyFShi/4enuSUm60V7y2KAINYcuxl5GL9Aq8oSBP0yKdNK6vx1MpsIdgL7FX7cn4O2MI3BkH/dq7WyCg==")!
    static let grantKid = "g1"

    /// The same bytes signed by g2 — a valid signature by the wrong key. Any
    /// test that accepts this is not verifying anything.
    static let grantSignatureByWrongKey = Data(base64Encoded: "WWw8EbOFUeveYXov9F6h2/peygI6SihSFBpPzv9Pp8Xm59QFV2eH6HQNJLGa3fnw+3e4sYcXY4Mkb432P+03Cg==")!

    static let policyDigest = "sha256:60d5ec96060ffd4cf70ce897ddc21e27ce9b96a9245a84a096bac921f0aa3541"
}
