import Foundation

/// Escalating friction for repeated Solo Emergency Overrides (NORTHSTAR §25).
///
/// Each step is expressed as a `FrictionRequirement` rather than a bare
/// duration, because the product intent is *active* effort, not elapsed
/// wall-clock time while the user does something else.
public struct SoloEscalation: Codable, Equatable, Sendable {
    /// How far back granted solo overrides count as "recent".
    public var recentWindow: TimeInterval
    /// Requirements by number of recent solo overrides; the last entry applies
    /// to all further repetitions.
    public var steps: [FrictionRequirement]

    public init(recentWindow: TimeInterval = 30 * 24 * 3600,
                steps: [FrictionRequirement] = FrictionRequirement.defaultEscalation) {
        self.recentWindow = recentWindow
        self.steps = steps
    }

    public func requirement(recentSoloCount: Int) -> FrictionRequirement {
        guard let last = steps.last else { return FrictionRequirement(effortUnits: 0, minimumElapsed: 0) }
        guard recentSoloCount < steps.count else { return last }
        return steps[max(0, recentSoloCount)]
    }

    public func isAtLeastAsHard(as other: SoloEscalation) -> Bool {
        guard recentWindow >= other.recentWindow else { return false }
        guard steps.count >= other.steps.count else { return false }
        return zip(steps, other.steps).allSatisfy { $0.isAtLeastAsHard(as: $1) }
    }
}

/// The escape rules attached to a commitment. These harden with it (NORTHSTAR §26).
public struct OverridePolicy: Codable, Equatable, Sendable {
    /// Accountability approvals needed for an Accountability Override.
    public var approvalsRequired: Int
    /// How long the accountability request must wait, unsatisfied, before the
    /// Solo Override becomes available, in seconds.
    public var accountabilityWindow: TimeInterval
    public var soloEscalation: SoloEscalation

    public init(approvalsRequired: Int,
                accountabilityWindow: TimeInterval,
                soloEscalation: SoloEscalation = SoloEscalation()) {
        self.approvalsRequired = approvalsRequired
        self.accountabilityWindow = accountabilityWindow
        self.soloEscalation = soloEscalation
    }

    public func isAtLeastAsHard(as other: OverridePolicy) -> Bool {
        approvalsRequired >= other.approvalsRequired
            && accountabilityWindow >= other.accountabilityWindow
            && soloEscalation.isAtLeastAsHard(as: other.soloEscalation)
    }
}

/// An exercise commitment: the contract itself, and the Gate it closes.
public struct Commitment: Codable, Equatable, Identifiable, Sendable {
    /// Fraction of the time-to-deadline that caps the correction window for
    /// short-fuse commitments (NORTHSTAR §11): a 2-hour-away commitment with a
    /// 2-hour configured window hardens after 2h × 1/8 = 15 minutes.
    public static let hardeningFraction = 0.125

    public let id: UUID
    public var title: String
    public var requirement: Requirement
    /// The moment this commitment's eligible period opens. A workout only counts
    /// toward it if the workout started at or after this instant.
    ///
    /// For a one-off this is creation time — you cannot commit to a run you have
    /// already done. For an occurrence generated by a plan it is midnight at the
    /// start of that occurrence's calendar day (clamped to never precede the
    /// plan's creation), so Monday's run cannot satisfy Wednesday's obligation.
    /// There is deliberately no upper bound: a late workout must still be able to
    /// clear outstanding debt (NORTHSTAR §16).
    public var eligibleFrom: Date
    public var deadline: Date
    public let createdAt: Date
    public var configuredCorrectionWindow: TimeInterval
    public var overridePolicy: OverridePolicy
    /// What this Gate takes away while it is unsatisfied. Restrictions belong to
    /// Gates, not to the account.
    public var restrictions: RestrictionProfile
    public var rewardEligible: Bool
    /// Optional warning lead time before the deadline, in seconds.
    public var warningLead: TimeInterval?
    /// Set when this commitment was generated by a recurring plan.
    public var planID: UUID?

    public init(id: UUID = UUID(),
                title: String,
                requirement: Requirement,
                eligibleFrom: Date? = nil,
                deadline: Date,
                createdAt: Date,
                configuredCorrectionWindow: TimeInterval,
                overridePolicy: OverridePolicy,
                restrictions: RestrictionProfile = .none,
                rewardEligible: Bool = true,
                warningLead: TimeInterval? = nil,
                planID: UUID? = nil) {
        self.id = id
        self.title = title
        self.requirement = requirement
        self.eligibleFrom = eligibleFrom ?? createdAt
        self.deadline = deadline
        self.createdAt = createdAt
        self.configuredCorrectionWindow = configuredCorrectionWindow
        self.overridePolicy = overridePolicy
        self.restrictions = restrictions
        self.rewardEligible = rewardEligible
        self.warningLead = warningLead
        self.planID = planID
    }

    /// When the correction window ends and the contract hardens.
    public var hardensAt: Date {
        let timeToDeadline = max(0, deadline.timeIntervalSince(createdAt))
        let window = min(configuredCorrectionWindow, timeToDeadline * Self.hardeningFraction)
        return createdAt.addingTimeInterval(window)
    }

    public func isHardened(at date: Date) -> Bool { date >= hardensAt }

    /// Whether `self` is at least as hard as `other` in every hardened dimension.
    /// An earlier deadline is harder; a later `eligibleFrom` is harder (a
    /// narrower window in which to earn it); a stricter restriction profile is
    /// harder; reward eligibility is neutral and must not change.
    func isAtLeastAsHard(as other: Commitment) -> Bool {
        requirement.isAtLeastAsHard(as: other.requirement)
            && deadline <= other.deadline
            && eligibleFrom >= other.eligibleFrom
            && restrictions.isAtLeastAsStrict(as: other.restrictions)
            && overridePolicy.isAtLeastAsHard(as: other.overridePolicy)
            && rewardEligible == other.rewardEligible
    }
}

// MARK: - Backward-compatible decoding

extension Commitment {
    private enum CodingKeys: String, CodingKey {
        case id, title, requirement, eligibleFrom, deadline, createdAt
        case configuredCorrectionWindow, overridePolicy, restrictions
        case rewardEligible, warningLead, planID
    }

    /// Ledger v1 commitments had no `eligibleFrom`, no `restrictions` and no
    /// `planID`. They decode with the window opening at creation, which is
    /// exactly the rule that was in force when they were written.
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(UUID.self, forKey: .id)
        title = try container.decode(String.self, forKey: .title)
        requirement = try container.decode(Requirement.self, forKey: .requirement)
        deadline = try container.decode(Date.self, forKey: .deadline)
        createdAt = try container.decode(Date.self, forKey: .createdAt)
        configuredCorrectionWindow = try container.decode(TimeInterval.self, forKey: .configuredCorrectionWindow)
        overridePolicy = try container.decode(OverridePolicy.self, forKey: .overridePolicy)
        rewardEligible = try container.decode(Bool.self, forKey: .rewardEligible)
        warningLead = try container.decodeIfPresent(TimeInterval.self, forKey: .warningLead)
        eligibleFrom = try container.decodeIfPresent(Date.self, forKey: .eligibleFrom) ?? createdAt
        restrictions = try container.decodeIfPresent(RestrictionProfile.self, forKey: .restrictions) ?? .none
        planID = try container.decodeIfPresent(UUID.self, forKey: .planID)
    }
}

/// A partial edit to a commitment. `nil` fields are left unchanged.
public struct CommitmentEdit: Codable, Equatable, Sendable {
    public var title: String?
    public var requirement: Requirement?
    public var eligibleFrom: Date?
    public var deadline: Date?
    public var overridePolicy: OverridePolicy?
    public var restrictions: RestrictionProfile?
    public var rewardEligible: Bool?
    public var warningLead: TimeInterval??

    public init(title: String? = nil,
                requirement: Requirement? = nil,
                eligibleFrom: Date? = nil,
                deadline: Date? = nil,
                overridePolicy: OverridePolicy? = nil,
                restrictions: RestrictionProfile? = nil,
                rewardEligible: Bool? = nil,
                warningLead: TimeInterval?? = nil) {
        self.title = title
        self.requirement = requirement
        self.eligibleFrom = eligibleFrom
        self.deadline = deadline
        self.overridePolicy = overridePolicy
        self.restrictions = restrictions
        self.rewardEligible = rewardEligible
        self.warningLead = warningLead
    }

    func applied(to commitment: Commitment) -> Commitment {
        var result = commitment
        if let title { result.title = title }
        if let requirement { result.requirement = requirement }
        if let eligibleFrom { result.eligibleFrom = eligibleFrom }
        if let deadline { result.deadline = deadline }
        if let overridePolicy { result.overridePolicy = overridePolicy }
        if let restrictions { result.restrictions = restrictions }
        if let rewardEligible { result.rewardEligible = rewardEligible }
        if let warningLead { result.warningLead = warningLead }
        return result
    }
}

public enum OverrideKind: String, Codable, Equatable, Sendable {
    case free
    case accountability
    case solo
}

/// Terminal states of a commitment. An unresolved commitment past its deadline
/// is *overdue* — a derived condition, not a resolution (NORTHSTAR §16: passing
/// the deadline does not eliminate the obligation).
public enum CommitmentResolution: Codable, Equatable, Sendable {
    case completed(at: Date)
    case overridden(OverrideKind, at: Date)
    case cancelled(at: Date)
}
